namespace NetPrints.Annotations
{
    /// <summary>The attribute definitions injected into every consuming compilation (contracts/annotations.md section 2), as C# 7.3 source.</summary>
    internal static class AttributeSources
    {
        public const string HintName = "NetPrintsAttributes.g.cs";

        public const string Source = @"// <auto-generated/> NetPrints.Annotations
namespace NetPrints.Annotations
{
    [global::Microsoft.CodeAnalysis.Embedded]
    [global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = true)]
    internal sealed class NetPrintsCatalogAttribute : global::System.Attribute
    {
        public NetPrintsCatalogAttribute(string assemblyName)
        {
            AssemblyName = assemblyName;
        }

        public string AssemblyName { get; }

        public string Id { get; set; }

        public string Profile { get; set; }

        public string[] Include { get; set; }

        public string[] Exclude { get; set; }

        public string AccessorName { get; set; }
    }

    [global::Microsoft.CodeAnalysis.Embedded]
    [global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct | global::System.AttributeTargets.Interface | global::System.AttributeTargets.Enum)]
    internal sealed class NetPrintsTypeAttribute : global::System.Attribute
    {
        public string DisplayName { get; set; }

        public string Category { get; set; }
    }

    [global::Microsoft.CodeAnalysis.Embedded]
    [global::System.AttributeUsage(global::System.AttributeTargets.Method)]
    internal sealed class NetPrintsNodeAttribute : global::System.Attribute
    {
        public string DisplayName { get; set; }

        public string Category { get; set; }

        public string[] Keywords { get; set; }
    }

    [global::Microsoft.CodeAnalysis.Embedded]
    [global::System.AttributeUsage(global::System.AttributeTargets.All & ~global::System.AttributeTargets.Assembly)]
    internal sealed class NetPrintsIgnoreAttribute : global::System.Attribute
    {
    }

    [global::Microsoft.CodeAnalysis.Embedded]
    [global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = true)]
    internal sealed class NetPrintsEmbeddedCatalogAttribute : global::System.Attribute
    {
        public NetPrintsEmbeddedCatalogAttribute(string id, int schemaVersion, string json)
        {
            Id = id;
            SchemaVersion = schemaVersion;
            Json = json;
        }

        public string Id { get; }

        public int SchemaVersion { get; }

        public string Json { get; }
    }
}
";
    }
}
