using System;
using System.IO;
using System.Linq;
using System.Reflection;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using NetPrints.Catalog.Tests.Format;
using NetPrints.Reflection;
using Xunit;

namespace NetPrints.Catalog.Tests.Emit;

/// <summary>CT-T14: the emitted C# compiles against <c>NetPrints.Catalog</c> and <c>Create()</c> returns a catalog equal to the JSON.</summary>
public sealed class CSharpFormatTests
{
    private const string Namespace = "Sample.Catalogs";

    private const string ClassName = "SampleCatalog";

    private static CSharpCompilation CreateCompilation(string source)
    {
        MetadataReference[] references =
        [
            .. FixtureCatalog.FrameworkReferences(),
            MetadataReference.CreateFromFile(typeof(CatalogLoader).Assembly.Location),
            MetadataReference.CreateFromFile(typeof(ITypeCatalog).Assembly.Location),
            MetadataReference.CreateFromFile(typeof(NetPrints.Core.TypeSpecifier).Assembly.Location),
        ];
        return CSharpCompilation.Create(
            "EmittedCatalog",
            [CSharpSyntaxTree.ParseText(source, new CSharpParseOptions(LanguageVersion.Latest))],
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary, nullableContextOptions: NullableContextOptions.Enable));
    }

    private static Assembly Compile(string source)
    {
        using MemoryStream stream = new();
        var result = CreateCompilation(source).Emit(stream, cancellationToken: TestContext.Current.CancellationToken);
        Assert.True(result.Success, string.Join(Environment.NewLine, result.Diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error)));
        return Assembly.Load(stream.ToArray());
    }

    private static Type EmittedClass(Assembly assembly) =>
        assembly.GetType($"{Namespace}.{ClassName}") ?? throw new InvalidOperationException("The emitted class is missing.");

    [Fact]
    public void EmittedCodeCompilesAndCreatesTheCatalog()
    {
        CatalogDocument document = SampleCatalog.Build();
        Type type = EmittedClass(Compile(CatalogCSharpEmitter.Emit(document, Namespace, ClassName)));

        var json = (string?)type.GetProperty("Json")?.GetValue(null);
        var created = (ITypeCatalog?)type.GetMethod("Create")?.Invoke(null, null);

        Assert.Equal(CanonicalCatalogWriter.Write(document), json);
        Assert.NotNull(created);
        ITypeCatalog expected = CatalogLoader.Load(document);
        Assert.Equal(expected.Info.Id, created.Info.Id);
        Assert.Equal(expected.Info.Version, created.Info.Version);
        Assert.Equal(expected.Info.CoveredAssemblyNames, created.Info.CoveredAssemblyNames);
        Assert.Equal(expected.GetNonStaticTypes().Select(t => t.ToString()), created.GetNonStaticTypes().Select(t => t.ToString()));
    }

    [Fact]
    public void EmittedCodeCompilesWithoutWarnings()
    {
        CSharpCompilation compilation = CreateCompilation(CatalogCSharpEmitter.Emit(SampleCatalog.Build(), Namespace, ClassName));

        Assert.Empty(compilation.GetDiagnostics(TestContext.Current.CancellationToken).Where(d => d.Severity >= DiagnosticSeverity.Warning));
    }

    [Fact]
    public void OutputIsDeterministicWithLfEndingsAndAHeader()
    {
        CatalogDocument document = SampleCatalog.Build();
        string first = CatalogCSharpEmitter.Emit(document, Namespace, ClassName);

        Assert.Equal(first, CatalogCSharpEmitter.Emit(document, Namespace, ClassName));
        Assert.StartsWith("// <auto-generated/> netprints catalog\n", first, StringComparison.Ordinal);
        Assert.DoesNotContain('\r', first);
        Assert.EndsWith("\n", first, StringComparison.Ordinal);
        Assert.Contains("namespace Sample.Catalogs\n{\n", first, StringComparison.Ordinal);
    }

    [Fact]
    public void JsonWithEveryEscapeSurvivesTheRoundTrip()
    {
        CatalogDocument document = SampleCatalog.Build();
        Type type = EmittedClass(Compile(CatalogCSharpEmitter.Emit(document, Namespace, ClassName)));

        var json = (string?)type.GetProperty("Json")?.GetValue(null);

        Assert.Equal(document.Types.Count, CatalogReader.Read(json ?? string.Empty).Types.Count);
    }

    [Theory]
    [InlineData("plain", "\"plain\"")]
    [InlineData("say \"hi\"", "\"say \\\"hi\\\"\"")]
    [InlineData("back\\slash", "\"back\\\\slash\"")]
    [InlineData("line\nbreak\r\ttab", "\"line\\nbreak\\r\\ttab\"")]
    [InlineData("bell\u0001", "\"bell\\u0001\"")]
    [InlineData("nul\0", "\"nul\\u0000\"")]
    [InlineData("sep\u2028\u2029next\u0085", "\"sep\\u2028\\u2029next\\u0085\"")]
    [InlineData("del\u007f", "\"del\\u007F\"")]
    [InlineData("accents éü", "\"accents éü\"")]
    [InlineData("smile \U0001F600", "\"smile \U0001F600\"")]
    [InlineData("", "\"\"")]
    public void LiteralEscapesWhatCSharpCannotHoldVerbatim(string value, string expected)
    {
        Assert.Equal(expected, CSharpLiteral.Quote(value));
    }

    [Fact]
    public void AnUnpairedSurrogateIsEscaped()
    {
        Assert.Equal("\"lone \\uD83D high \\uDE00 low\"", CSharpLiteral.Quote("lone \ud83d high \ude00 low"));
    }

    [Fact]
    public void QuotedLiteralsCompileBackToTheirValue()
    {
        string[] values = ["a\"b\\c", "\u0000\u0001\u001f\u007f\u0085\u2028", "\ud83d", "x\ny"];
        string source = "public static class L { public static readonly string[] All = [" + string.Join(", ", values.Select(CSharpLiteral.Quote)) + "]; }";

        Assembly assembly = Compile(source);
        var actual = (string[]?)assembly.GetType("L")?.GetField("All")?.GetValue(null);

        Assert.Equal(values, actual);
    }

    [Theory]
    [InlineData("", "Class")]
    [InlineData("Ns", "")]
    [InlineData("Ns", "1Bad")]
    [InlineData("Ns", "class")]
    [InlineData("Ns..Two", "Class")]
    [InlineData("Ns.", "Class")]
    public void InvalidNamesAreRejected(string @namespace, string className)
    {
        Assert.Throws<ArgumentException>(() => CatalogCSharpEmitter.Emit(SampleCatalog.Build(), @namespace, className));
    }
}
