using System;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using NetPrints.Catalog.Tests.Format;
using Xunit;

namespace NetPrints.Catalog.Tests.Emit;

/// <summary>T066: the shared embedded-catalog source is deterministic, block-scoped, C# 7.3 and carries the JSON as an attribute argument and as UTF-8 bytes.</summary>
public sealed class EmbeddedCatalogEmitterTests
{
    private const string AttributeStub = """
        namespace NetPrints.Annotations
        {
            [System.AttributeUsage(System.AttributeTargets.Assembly, AllowMultiple = true)]
            internal sealed class NetPrintsEmbeddedCatalogAttribute : System.Attribute
            {
                public NetPrintsEmbeddedCatalogAttribute(string id, int schemaVersion, string json) { Id = id; SchemaVersion = schemaVersion; Json = json; }

                public string Id { get; }

                public int SchemaVersion { get; }

                public string Json { get; }
            }
        }
        """;

    private static Assembly Compile(string emitted)
    {
        CSharpParseOptions parse = new(LanguageVersion.CSharp7_3);
        CSharpCompilation compilation = CSharpCompilation.Create(
            "Embedded",
            [CSharpSyntaxTree.ParseText(AttributeStub, parse), CSharpSyntaxTree.ParseText(emitted, parse)],
            FixtureCatalog.FrameworkReferences(),
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
        using MemoryStream stream = new();
        var result = compilation.Emit(stream, cancellationToken: TestContext.Current.CancellationToken);
        Assert.True(result.Success, string.Join(Environment.NewLine, result.Diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error)));
        return Assembly.Load(stream.ToArray());
    }

    [Fact]
    public void TheFileCompilesAtCSharp7AndTheAccessorsReturnTheCanonicalJson()
    {
        CatalogDocument document = SampleCatalog.Build();
        string json = CanonicalCatalogWriter.Write(document);

        Assembly assembly = Compile(EmbeddedCatalogEmitter.Emit(document, "My.Project", "Sample"));
        Type accessors = assembly.GetType("My.Project.NetPrintsCatalogs") ?? throw new InvalidOperationException("The accessor class is missing.");

        Assert.Equal(json, (string?)accessors.GetProperty("Sample")?.GetValue(null));
        Assert.Equal(Encoding.UTF8.GetBytes(json), (byte[]?)accessors.GetProperty("SampleUtf8")?.GetValue(null));
        Assert.Null(accessors.GetField("Sample"));
    }

    [Fact]
    public void TheAssemblyAttributeCarriesTheIdSchemaVersionAndJson()
    {
        CatalogDocument document = SampleCatalog.Build();

        Assembly assembly = Compile(EmbeddedCatalogEmitter.Emit(document, "My.Project", "Sample"));
        CustomAttributeData attribute = assembly.GetCustomAttributesData().Single(a => a.AttributeType.Name == "NetPrintsEmbeddedCatalogAttribute");

        Assert.Equal(document.Id, (string?)attribute.ConstructorArguments[0].Value);
        Assert.Equal(document.SchemaVersion, (int?)attribute.ConstructorArguments[1].Value);
        Assert.Equal(CanonicalCatalogWriter.Write(document), (string?)attribute.ConstructorArguments[2].Value);
    }

    [Fact]
    public void AMissingOrInvalidRootNamespaceUsesTheGlobalNamespaceWithoutANamespaceBlock()
    {
        CatalogDocument document = SampleCatalog.Build();

        foreach (string? rootNamespace in new string?[] { null, string.Empty, "not a namespace" })
        {
            string emitted = EmbeddedCatalogEmitter.Emit(document, rootNamespace, "Sample");

            Assert.DoesNotContain("namespace ", emitted, StringComparison.Ordinal);
            Assert.NotNull(Compile(emitted).GetType("NetPrintsCatalogs"));
        }
    }

    [Fact]
    public void TheOutputIsDeterministicBlockScopedWithLfEndings()
    {
        CatalogDocument document = SampleCatalog.Build();
        string first = EmbeddedCatalogEmitter.Emit(document, "My.Project", "Sample");

        Assert.Equal(first, EmbeddedCatalogEmitter.Emit(document, "My.Project", "Sample"));
        Assert.StartsWith("// <auto-generated/> NetPrints.Annotations\n", first, StringComparison.Ordinal);
        Assert.Contains("namespace My.Project\n{\n", first, StringComparison.Ordinal);
        Assert.DoesNotContain("const string", first, StringComparison.Ordinal);
        Assert.DoesNotContain('\r', first);
        Assert.EndsWith("}\n", first, StringComparison.Ordinal);
    }

    [Theory]
    [InlineData("catalogfixturelib", "Catalogfixturelib")]
    [InlineData("my-lib.core_x", "MyLibCoreX")]
    [InlineData("1st", "_1st")]
    [InlineData("---", "Catalog")]
    public void TheDefaultAccessorNameIsPascalCaseOfTheId(string id, string expected)
    {
        Assert.Equal(expected, EmbeddedCatalogEmitter.DefaultAccessorName(id));
    }

    [Theory]
    [InlineData("")]
    [InlineData("class")]
    [InlineData("1Bad")]
    public void AnInvalidAccessorNameIsRejected(string accessor)
    {
        Assert.Throws<ArgumentException>(() => EmbeddedCatalogEmitter.Emit(SampleCatalog.Build(), "Ns", accessor));
    }
}
