#nullable enable
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Formatting;
using NetPrints.Core;
using NetPrints.Graph;

namespace NetPrints.Translator
{
    /// <summary>
    /// Stateless helpers shared by <see cref="ExecutionGraphTranslator"/> and
    /// <see cref="ClassTranslator"/>: naming, literal formatting, graph traversal and C# formatting.
    /// </summary>
    public static class TranslatorUtil
    {
        /// <summary>
        /// Prefix prepended to every generated local variable name (see
        /// <see cref="GetUniqueVariableName"/>).
        /// </summary>
        public const string VariablePrefix = "var";

        /// <summary>
        /// Prefix used as the base name for temporary variables generated by
        /// <see cref="GetTemporaryVariableName"/> (multi-value returns, caught exceptions).
        /// </summary>
        public const string TemporaryVariablePrefix = "temp";

        /// <summary>
        /// Maps each <see cref="MemberVisibility"/> value to the C# keyword the translators emit for
        /// it.
        /// </summary>
        public readonly static Dictionary<MemberVisibility, string> VisibilityTokens = new Dictionary<MemberVisibility, string>()
        {
            [MemberVisibility.Private] = "private",
            [MemberVisibility.Protected] = "protected",
            [MemberVisibility.Public] = "public",
            [MemberVisibility.Internal] = "internal",
        };

        private const int TemporaryVariableNameLength = 16;

        /// <summary>
        /// Gets a temporary variable name.
        /// </summary>
        /// <returns>Temporary variable name.</returns>
        public static string GetTemporaryVariableName(Random random)
        {
            const string chars = "abcdefghijklmnopqrstuvwxyz";

            string name = TemporaryVariablePrefix;
            int additionalLength = TemporaryVariableNameLength - name.Length;
            if (additionalLength > 0)
            {
                string addition = new string(Enumerable.Repeat(chars, additionalLength).Select(s => s[random.Next(s.Length)]).ToArray());
                addition = addition[0].ToString().ToUpper() + string.Join("", addition.Skip(1));
                name += addition;
            }

            return name;
        }

        /// <summary>
        /// Translates an object into a literal value (eg. a float 32.32 -> "32.32f")
        /// </summary>
        /// <param name="obj">Object value to translate. Null translates to the "null" literal.</param>
        /// <param name="type">Specifier for the type of the literal.</param>
        /// <returns></returns>
        public static string ObjectToLiteral(object? obj, TypeSpecifier type)
        {
            // Interpret object string as enum field
            if (type.IsEnum)
            {
                return $"{type}.{obj}";
            }

            // Null
            if (obj is null)
            {
                return "null";
            }

            // Numbers are culture-invariant. obj is a boxed built-in value type here (int, double,
            // ...); none of their ToString() overrides ever return null.
            string invariant = obj is System.IFormattable formattable
                ? formattable.ToString(null, System.Globalization.CultureInfo.InvariantCulture)
                : obj.ToString()!;

            if (type == TypeSpecifier.FromType<string>())
            {
                // type == string means obj is the literal's own boxed string value.
                return Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral((string)obj, quote: true);
            }
            else if (type == TypeSpecifier.FromType<char>() && obj is char c)
            {
                return Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(c, quote: true);
            }
            else if (type == TypeSpecifier.FromType<bool>() && obj is bool b)
            {
                return b ? "true" : "false";
            }
            else if (type == TypeSpecifier.FromType<float>())
            {
                return obj is float f && NonFiniteLiteral(f, "float") is { } floatLiteral ? floatLiteral : $"{invariant}F";
            }
            else if (type == TypeSpecifier.FromType<double>())
            {
                return obj is double d && NonFiniteLiteral(d, "double") is { } doubleLiteral ? doubleLiteral : $"{invariant}D";
            }
            else if (type == TypeSpecifier.FromType<uint>())
            {
                return $"{invariant}U";
            }
            else if (type == TypeSpecifier.FromType<long>())
            {
                return $"{invariant}L";
            }
            else if (type == TypeSpecifier.FromType<ulong>())
            {
                return $"{invariant}UL";
            }
            else if (type == TypeSpecifier.FromType<decimal>())
            {
                return $"{invariant}M";
            }
            else
            {
                return invariant;
            }
        }

        /// <summary>
        /// The static-field spelling of a non-finite float or double ("float.NaN",
        /// "double.PositiveInfinity", …), or null for a finite value. NaN and Infinity have no
        /// numeric literal in C#, so <see cref="ObjectToLiteral"/> must not emit them as a suffixed
        /// number ("NaND", "InfinityD"), which fails to compile.
        /// </summary>
        private static string? NonFiniteLiteral(double value, string typeName) => value switch
        {
            double.NaN => $"{typeName}.NaN",
            double.PositiveInfinity => $"{typeName}.PositiveInfinity",
            double.NegativeInfinity => $"{typeName}.NegativeInfinity",
            _ => null,
        };

        /// <summary>
        /// Returns the first name not already contained in a list of names by
        /// trying to generate a unique name based on the given name.
        /// Includes a prefix in front of the name.
        /// </summary>
        /// <param name="name">Name to make unique.</param>
        /// <param name="names">List of names already existing.</param>
        /// <returns>Name based on name but not contained in names.</returns>
        public static string GetUniqueVariableName(string name, IList<string> names)
        {
            // Don't allow illegal characters in the name
            // TODO: Make this more general
            name = name.Replace("+", "_").Replace("[", "").Replace("]", "Array").Replace(",", "");

            int i = 1;

            while (true)
            {
                string uniqueName = i == 1 ? $"{VariablePrefix}{name}" : $"{VariablePrefix}{name}{i}";

                if (!names.Contains(uniqueName))
                {
                    return uniqueName;
                }

                i++;
            }
        }

        private static void AddAllNodes(Node node, ref HashSet<Node> nodes)
        {
            nodes.Add(node);

            foreach (NodeOutputExecPin pin in node.OutputExecPins)
            {
                if (pin.OutgoingPin != null && !nodes.Contains(pin.OutgoingPin.Node))
                {
                    AddAllNodes(pin.OutgoingPin.Node, ref nodes);
                }
            }

            foreach (NodeInputDataPin pin in node.InputDataPins)
            {
                if (pin.IncomingPin != null && !nodes.Contains(pin.IncomingPin.Node))
                {
                    AddAllNodes(pin.IncomingPin.Node, ref nodes);
                }
            }

            foreach (NodeInputTypePin pin in node.InputTypePins)
            {
                if (pin.IncomingPin != null && !nodes.Contains(pin.IncomingPin.Node))
                {
                    AddAllNodes(pin.IncomingPin.Node, ref nodes);
                }
            }
        }

        /// <summary>
        /// Gets all nodes contained in a graph.
        /// </summary>
        /// <param name="graph">Graph containing the nodes.</param>
        /// <returns>Nodes contained in the graph.</returns>
        public static IEnumerable<Node> GetAllNodesInExecGraph(ExecutionGraph graph)
        {
            HashSet<Node> nodes = new HashSet<Node>();

            AddAllNodes(graph.EntryNode, ref nodes);

            return nodes;
        }

        private static void AddExecNodes(Node node, ref HashSet<Node> nodes)
        {
            nodes.Add(node);

            foreach (NodeOutputExecPin pin in node.OutputExecPins)
            {
                if (pin.OutgoingPin != null && !nodes.Contains(pin.OutgoingPin.Node))
                {
                    AddExecNodes(pin.OutgoingPin.Node, ref nodes);
                }
            }
        }

        /// <summary>
        /// Gets all execution contained nodes in a graph
        /// </summary>
        /// <param name="graph">Graph containing the execution nodes.</param>
        /// <returns>Execution nodes contained in the graph.</returns>
        public static IEnumerable<Node> GetExecNodesInExecGraph(ExecutionGraph graph)
        {
            HashSet<Node> nodes = new HashSet<Node>();

            AddExecNodes(graph.EntryNode, ref nodes);

            return nodes;
        }

        private static void AddDependentPureNodes(Node node, ref HashSet<Node> nodes)
        {
            // Only add pure nodes (the initial node might not be pure)
            if (node.IsPure)
            {
                nodes.Add(node);
            }

            foreach (NodeInputDataPin pin in node.InputDataPins)
            {
                if (pin.IncomingPin?.Node.IsPure == true && !nodes.Contains(pin.IncomingPin.Node))
                {
                    AddDependentPureNodes(pin.IncomingPin.Node, ref nodes);
                }
            }
        }

        /// <summary>
        /// Gets all pure nodes a node depends on.
        /// </summary>
        /// <param name="node">Node whose dependent pure nodes to get.</param>
        /// <returns>Pure nodes the node depends on.</returns>
        public static IEnumerable<Node> GetDependentPureNodes(Node node)
        {
            HashSet<Node> nodes = new HashSet<Node>();

            AddDependentPureNodes(node, ref nodes);

            return nodes;
        }

        /// <summary>
        /// Gets all pure nodes a node depends on sorted by depth.
        /// </summary>
        /// <param name="node">Node whose dependent pure nodes to get.</param>
        /// <returns>Pure nodes the node depends on sorted by depth.</returns>
        public static IEnumerable<Node> GetSortedPureNodes(Node node)
        {
            var dependentNodes = GetDependentPureNodes(node);
            List<Node> remainingNodes = new List<Node>(dependentNodes);
            List<Node> sortedNodes = new List<Node>();

            List<Node> newNodes = new List<Node>();

            do
            {
                newNodes.Clear();

                foreach (Node evalNode in remainingNodes)
                {
                    // Check whether all of this node's dependencies have been evaluated
                    if (evalNode.InputDataPins.All(inNode => inNode.IncomingPin?.Node.IsPure != true || sortedNodes.Contains(inNode.IncomingPin.Node)))
                    {
                        newNodes.Add(evalNode);
                    }
                }

                // Add newly found nodes
                foreach (Node newNode in newNodes)
                {
                    remainingNodes.Remove(newNode);
                }

                sortedNodes.AddRange(newNodes);
            }
            while (newNodes.Count > 0 && remainingNodes.Count > 0);

            Debug.Assert(remainingNodes.Count == 0, "Impossible to evaluate all nodes (cyclic dependencies?)");

            return sortedNodes;
        }

        /// <summary>
        /// Formats a C# source string with Roslyn's default formatter (indentation and whitespace
        /// normalization) using an ad hoc workspace.
        /// </summary>
        /// <param name="code">C# source to format. Must be parseable (need not be a full compilation unit).</param>
        /// <returns>The formatted source.</returns>
        public static string FormatCode(string code)
        {
            SyntaxTree syntaxTree = CSharpSyntaxTree.ParseText(code);
            SyntaxNode formatted = Formatter.Format(syntaxTree.GetCompilationUnitRoot(), new AdhocWorkspace()).NormalizeWhitespace();
            return formatted.ToFullString();
        }
    }
}
