// <auto-generated>
//     Generated by NetPrints from HelloWorld.Program.netpc.json. Do not edit.
// </auto-generated>
namespace HelloWorld
{
    public class Program : System.Object
    {
        // Main
        public static void Main()
        {
            // Variables
            // Console.WriteLine
            System.Console.WriteLine("Hello, World!");
        // Return
        }
    }
}
