using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging.Abstractions;
using NetPrints.Compilation;
using NetPrints.Core;
using NetPrints.Extensibility.Loading;
using NetPrints.Generation;
using NetPrints.Graph;
using NetPrints.Serialization;
using NetPrints.Serialization.Documents;
using NetPrints.Serialization.Json;
using NetPrints.Serialization.Mapping;
using NetPrints.Serialization.Migrations;
using NetPrints.Tests.Extensibility;
using NetPrints.Tests.Samples;
using NetPrints.Translator;
using Xunit;

namespace NetPrints.Tests.Projects
{
    /// <summary>
    /// PS-T06 (project-system.md §7): the generated file's header, its "\n"-only line endings,
    /// determinism across two runs, and that its content equals <see cref="GraphCodeGenerator.RenderFile"/>
    /// of the same class's editor translation.
    /// </summary>
    public class GraphCodeGeneratorTests
    {
        private static NodeDocumentConverterRegistry NewRegistry() => new(NodeDocumentConverterRegistry.BuiltIn, []);

        private static JsonDocumentFormat NewJsonFormat(NodeDocumentConverterRegistry registry) =>
            new(new NetPrintsJsonOptions(registry), new DocumentMigrator([], NullLogger<DocumentMigrator>.Instance));

        private static async Task<string> WriteCanonicalGraphAsync(string directory)
        {
            string sourcePath = Path.Combine(SampleProjectFactory.FindRepositoryRoot(), "samples", "HelloWorld", "HelloWorld.Program.netpc.json");
            string graphPath = Path.Combine(directory, "HelloWorld.Program.netpc.json");
            await using (FileStream input = File.OpenRead(sourcePath))
            await using (FileStream output = File.Create(graphPath))
            {
                await input.CopyToAsync(output, TestContext.Current.CancellationToken);
            }

            return graphPath;
        }

        private static async Task<ClassGraph> LoadClassAsync(string graphPath)
        {
            NodeDocumentConverterRegistry registry = NewRegistry();
            var mapper = new DocumentMapper(registry, NullLogger<DocumentMapper>.Instance);
            JsonDocumentFormat jsonFormat = NewJsonFormat(registry);
            var id = new DocumentId(Path.GetFileName(graphPath));

            ClassDocument document;
            using (FileStream input = File.OpenRead(graphPath))
            {
                document = await jsonFormat.ReadClassAsync(input, id, TestContext.Current.CancellationToken);
            }

            var issues = new List<DocumentIssue>();
            Project project = TestProjects.Create("HelloWorld", "HelloWorld");
            return mapper.FromDocument(document, project, issues, id);
        }

        private static GraphCodeGenerator NewGenerator()
        {
            NodeDocumentConverterRegistry registry = NewRegistry();
            var mapper = new DocumentMapper(registry, NullLogger<DocumentMapper>.Instance);
            var formats = new DocumentFormatRegistry([NewJsonFormat(registry)]);
            return new GraphCodeGenerator(ExtensionTestSupport.Load(ExtensionLoaderOptions.BuiltInOnly), formats, mapper);
        }

        [Fact]
        public async Task GeneratedFileHasHeaderUnixEndingsAndIsDeterministic()
        {
            string directory = Directory.CreateTempSubdirectory("netprints-generator-tests-").FullName;
            try
            {
                string graphPath = await WriteCanonicalGraphAsync(directory);
                string outputPath = Path.Combine(directory, "HelloWorld.Program.netpc.g.cs");

                var request = new GenerateRequest(
                    Path.Combine(directory, "HelloWorld.csproj"), "HelloWorld", "netprints.default",
                    [new GraphJob(graphPath, outputPath)], []);

                GraphCodeGenerator generator = NewGenerator();

                IReadOnlyList<GeneratedFileResult> firstResults = await generator.GenerateAsync(request, TestContext.Current.CancellationToken);
                GeneratedFileResult first = Assert.Single(firstResults);
                Assert.True(first.Written);
                Assert.Empty(first.Diagnostics);

                string firstContent = await File.ReadAllTextAsync(outputPath, TestContext.Current.CancellationToken);
                Assert.StartsWith(
                    "// <auto-generated>\n//     Generated by NetPrints from HelloWorld.Program.netpc.json. Do not edit.\n// </auto-generated>\n",
                    firstContent, StringComparison.Ordinal);
                Assert.DoesNotContain('\r', firstContent);
                Assert.EndsWith("\n", firstContent, StringComparison.Ordinal);
                Assert.False(firstContent.EndsWith("\n\n", StringComparison.Ordinal));

                byte[] firstBytes = await File.ReadAllBytesAsync(outputPath, TestContext.Current.CancellationToken);

                // Determinism: a second run of the same request (nothing changed) neither rewrites the
                // file nor changes its bytes.
                IReadOnlyList<GeneratedFileResult> secondResults = await generator.GenerateAsync(request, TestContext.Current.CancellationToken);
                GeneratedFileResult second = Assert.Single(secondResults);
                Assert.False(second.Written);

                byte[] secondBytes = await File.ReadAllBytesAsync(outputPath, TestContext.Current.CancellationToken);
                Assert.Equal(firstBytes, secondBytes);

                ClassGraph cls = await LoadClassAsync(graphPath);
                TranslatedClass translated = new ClassTranslator(TranslationEnvironment.BuiltIn).Translate(cls);
                string expected = GraphCodeGenerator.RenderFile(translated, "HelloWorld.Program.netpc.json");
                Assert.Equal(expected, firstContent);
            }
            finally
            {
                Directory.Delete(directory, recursive: true);
            }
        }

        /// <summary>Builds a class whose only method calls <see cref="Console.WriteLine(string)"/>
        /// with its argument pin left unconnected and no explicit default, so translating it throws
        /// NPT008 (R1-02).</summary>
        private static ClassGraph BuildClassWithUnsetRequiredInput(string className)
        {
            var cls = new ClassGraph { Name = className, Namespace = "GenTests" };
            var method = new MethodGraph("Run") { Class = cls, Visibility = MemberVisibility.Public };

            TypeSpecifier stringType = TypeSpecifier.FromType<string>();
            var writeConsoleSpecifier = new MethodSpecifier("WriteLine",
                new[] { new MethodParameter("value", stringType, MethodParameterPassType.Default, false, null) },
                Array.Empty<BaseType>(), MethodModifiers.None, MemberVisibility.Public,
                TypeSpecifier.FromType(typeof(Console)), Array.Empty<BaseType>());
            var writeConsoleNode = new CallMethodNode(method, writeConsoleSpecifier);

            GraphUtil.ConnectExecPins(method.EntryNode.InitialExecutionPin, writeConsoleNode.InputExecPins[0]);
            GraphUtil.ConnectExecPins(writeConsoleNode.OutputExecPins[0], method.ReturnNodes.First().InputExecPins[0]);

            // writeConsoleNode.ArgumentPins[0] is intentionally left unconnected with no default.
            cls.Methods.Add(method);
            return cls;
        }

        private static async Task<string> WriteGraphAsync(string directory, ClassGraph cls)
        {
            NodeDocumentConverterRegistry registry = NewRegistry();
            var mapper = new DocumentMapper(registry, NullLogger<DocumentMapper>.Instance);
            JsonDocumentFormat jsonFormat = NewJsonFormat(registry);
            ClassDocument document = mapper.ToDocument(cls);

            string graphPath = Path.Combine(directory, $"{cls.Name}.netpc.json");
            using var buffer = new MemoryStream();
            await jsonFormat.WriteClassAsync(document, buffer, TestContext.Current.CancellationToken);
            await File.WriteAllBytesAsync(graphPath, buffer.ToArray(), TestContext.Current.CancellationToken);
            return graphPath;
        }

        // R1-02: a graph that fails to translate is reported as an NPT008 diagnostic (the canonical
        // line includes it) instead of throwing, and a later graph in the same request still
        // generates — the generator would exit 1 for this request, not 3.
        [Fact]
        public async Task GenerateAsyncReportsATranslationFailureAsNpt008AndStillGeneratesLaterGraphs()
        {
            string directory = Directory.CreateTempSubdirectory("netprints-generator-npt008-").FullName;
            try
            {
                string failingGraphPath = await WriteGraphAsync(directory, BuildClassWithUnsetRequiredInput("Failing"));
                string okGraphPath = await WriteCanonicalGraphAsync(directory);
                string failingOutputPath = Path.Combine(directory, "Failing.netpc.g.cs");
                string okOutputPath = Path.Combine(directory, "HelloWorld.Program.netpc.g.cs");

                var request = new GenerateRequest(
                    Path.Combine(directory, "Gen.csproj"), "GenTests", "netprints.default",
                    [new GraphJob(failingGraphPath, failingOutputPath), new GraphJob(okGraphPath, okOutputPath)], []);

                GraphCodeGenerator generator = NewGenerator();
                IReadOnlyList<GeneratedFileResult> results = await generator.GenerateAsync(request, TestContext.Current.CancellationToken);

                Assert.Equal(2, results.Count);

                GeneratedFileResult failing = results[0];
                Assert.False(failing.Written);
                CodeDiagnostic diagnostic = Assert.Single(failing.Diagnostics);
                Assert.Equal(CodeDiagnosticSeverity.Error, diagnostic.Severity);
                Assert.Equal(TranslationDiagnosticCodes.UnsetRequiredInput, diagnostic.Id);
                Assert.Equal(failingGraphPath, diagnostic.SourcePath);
                Assert.StartsWith($"{failingGraphPath}: error NPT008:", CodeDiagnosticFormat.ToCanonicalLine(diagnostic), StringComparison.Ordinal);
                Assert.False(File.Exists(failingOutputPath));

                // The request did not abort: the graph after the failing one still generated.
                GeneratedFileResult ok = results[1];
                Assert.True(ok.Written);
                Assert.Empty(ok.Diagnostics);
                Assert.True(File.Exists(okOutputPath));
            }
            finally
            {
                Directory.Delete(directory, recursive: true);
            }
        }

        [Fact]
        public void RenderFileNormalizesLineEndingsAndTrailingNewline()
        {
            var translated = new TranslatedClass("Foo", "public class Foo\r\n{\r\n}\r\n\r\n", SourceMap.Empty);
            string rendered = GraphCodeGenerator.RenderFile(translated, "Foo.netpc.json");

            Assert.DoesNotContain('\r', rendered);
            Assert.Equal(
                "// <auto-generated>\n//     Generated by NetPrints from Foo.netpc.json. Do not edit.\n// </auto-generated>\npublic class Foo\n{\n}\n",
                rendered);
        }
    }
}
