using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using NetPrints.Core;
using NetPrints.Generator;
using NetPrints.Serialization;
using NetPrints.Serialization.Documents;
using NetPrints.Serialization.Json;
using NetPrints.Serialization.Legacy;
using NetPrints.Serialization.Mapping;
using NetPrints.Serialization.Migrations;
using NetPrints.Tests.Samples;
using NetPrints.Translator;
using Xunit;

namespace NetPrints.Tests.Projects
{
    /// <summary>
    /// PS-T06 (project-system.md §7): the generated file's header, its "\n"-only line endings,
    /// determinism across two runs, and that its content equals <see cref="GraphCodeGenerator.RenderFile"/>
    /// of the same class's editor translation.
    /// </summary>
    public class GraphCodeGeneratorTests
    {
        private static NodeDocumentConverterRegistry NewRegistry() => new(NodeDocumentConverterRegistry.BuiltIn, []);

        private static JsonDocumentFormat NewJsonFormat(NodeDocumentConverterRegistry registry) =>
            new(new NetPrintsJsonOptions(registry), new DocumentMigrator([]));

        private static async Task<string> WriteCanonicalGraphAsync(string directory)
        {
            string legacyPath = Path.Combine(SampleProjectFactory.FindRepositoryRoot(), "samples", "HelloWorld", "HelloWorld.Program.netpc");
            var id = new DocumentId("HelloWorld.Program.netpc.json");

            var mapper = new DocumentMapper(NewRegistry());
            var legacyFormat = new LegacyXmlDocumentFormat(mapper);

            ClassDocument document;
            using (FileStream input = File.OpenRead(legacyPath))
            {
                document = await legacyFormat.ReadClassAsync(input, id, TestContext.Current.CancellationToken);
            }

            string graphPath = Path.Combine(directory, "HelloWorld.Program.netpc.json");
            JsonDocumentFormat jsonFormat = NewJsonFormat(NewRegistry());
            await using (FileStream output = File.Create(graphPath))
            {
                await jsonFormat.WriteClassAsync(document, output, TestContext.Current.CancellationToken);
            }

            return graphPath;
        }

        private static async Task<ClassGraph> LoadClassAsync(string graphPath)
        {
            NodeDocumentConverterRegistry registry = NewRegistry();
            var mapper = new DocumentMapper(registry);
            JsonDocumentFormat jsonFormat = NewJsonFormat(registry);
            var id = new DocumentId(Path.GetFileName(graphPath));

            ClassDocument document;
            using (FileStream input = File.OpenRead(graphPath))
            {
                document = await jsonFormat.ReadClassAsync(input, id, TestContext.Current.CancellationToken);
            }

            var issues = new List<DocumentIssue>();
            Project project = Project.CreateNew("HelloWorld", "HelloWorld", addDefaultReferences: false);
            return mapper.FromDocument(document, project, issues, id);
        }

        private static GraphCodeGenerator NewGenerator()
        {
            NodeDocumentConverterRegistry registry = NewRegistry();
            var mapper = new DocumentMapper(registry);
            var formats = new DocumentFormatRegistry([NewJsonFormat(registry)]);
            return new GraphCodeGenerator(formats, mapper);
        }

        [Fact]
        public async Task GeneratedFileHasHeaderUnixEndingsAndIsDeterministic()
        {
            string directory = Directory.CreateTempSubdirectory("netprints-generator-tests-").FullName;
            try
            {
                string graphPath = await WriteCanonicalGraphAsync(directory);
                string outputPath = Path.Combine(directory, "HelloWorld.Program.netpc.g.cs");

                var request = new GenerateRequest(
                    Path.Combine(directory, "HelloWorld.csproj"), "HelloWorld", "netprints.default",
                    [new GraphJob(graphPath, outputPath)], []);

                GraphCodeGenerator generator = NewGenerator();

                IReadOnlyList<GeneratedFileResult> firstResults = await generator.GenerateAsync(request, TestContext.Current.CancellationToken);
                GeneratedFileResult first = Assert.Single(firstResults);
                Assert.True(first.Written);
                Assert.Empty(first.Diagnostics);

                string firstContent = await File.ReadAllTextAsync(outputPath, TestContext.Current.CancellationToken);
                Assert.StartsWith(
                    "// <auto-generated>\n//     Generated by NetPrints from HelloWorld.Program.netpc.json. Do not edit.\n// </auto-generated>\n",
                    firstContent, StringComparison.Ordinal);
                Assert.DoesNotContain('\r', firstContent);
                Assert.EndsWith("\n", firstContent, StringComparison.Ordinal);
                Assert.False(firstContent.EndsWith("\n\n", StringComparison.Ordinal));

                byte[] firstBytes = await File.ReadAllBytesAsync(outputPath, TestContext.Current.CancellationToken);

                // Determinism: a second run of the same request (nothing changed) neither rewrites the
                // file nor changes its bytes.
                IReadOnlyList<GeneratedFileResult> secondResults = await generator.GenerateAsync(request, TestContext.Current.CancellationToken);
                GeneratedFileResult second = Assert.Single(secondResults);
                Assert.False(second.Written);

                byte[] secondBytes = await File.ReadAllBytesAsync(outputPath, TestContext.Current.CancellationToken);
                Assert.Equal(firstBytes, secondBytes);

                ClassGraph cls = await LoadClassAsync(graphPath);
                string translated = new ClassTranslator().TranslateClass(cls);
                string expected = GraphCodeGenerator.RenderFile(translated, "HelloWorld.Program.netpc.json");
                Assert.Equal(expected, firstContent);
            }
            finally
            {
                Directory.Delete(directory, recursive: true);
            }
        }

        [Fact]
        public void RenderFileNormalizesLineEndingsAndTrailingNewline()
        {
            string rendered = GraphCodeGenerator.RenderFile("public class Foo\r\n{\r\n}\r\n\r\n", "Foo.netpc.json");

            Assert.DoesNotContain('\r', rendered);
            Assert.Equal(
                "// <auto-generated>\n//     Generated by NetPrints from Foo.netpc.json. Do not edit.\n// </auto-generated>\npublic class Foo\n{\n}\n",
                rendered);
        }
    }
}
