<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>NetPrints.Core</AssemblyName>
    <Version>0.0.7</Version>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Copyright>Robin Kahlow 2018</Copyright>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
  </ItemGroup>
</Project>
