using System;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis.CSharp;

namespace NetPrints.Catalog;

/// <summary>
/// Emits a catalog as a C# file (contracts/catalog.md §4): the canonical JSON as a constant and a factory that loads it
/// as a type catalog. Shared source: no file access.
/// </summary>
public static class CatalogCSharpEmitter
{
    private const string Header = "// <auto-generated/> netprints catalog";

    /// <summary>Emits <paramref name="document"/> as C#.</summary>
    /// <param name="document">The catalog.</param>
    /// <param name="namespace">The namespace of the emitted class: identifiers separated by dots.</param>
    /// <param name="className">The name of the emitted <c>internal static partial</c> class.</param>
    /// <returns>The file text, LF line endings, ending in a newline; the same text for the same catalog.</returns>
    /// <exception cref="ArgumentException"><paramref name="namespace"/> or <paramref name="className"/> is not a valid C# name.</exception>
    public static string Emit(CatalogDocument document, string @namespace, string className)
    {
        Guard.NotNull(document, nameof(document));
        Guard.NotNull(@namespace, nameof(@namespace));
        Guard.NotNull(className, nameof(className));
        if (@namespace.Length == 0 || !@namespace.Split('.').All(IsIdentifier))
        {
            throw new ArgumentException($"'{@namespace}' is not a valid namespace.", nameof(@namespace));
        }

        if (!IsIdentifier(className))
        {
            throw new ArgumentException($"'{className}' is not a valid class name.", nameof(className));
        }

        return new StringBuilder()
            .Append(Header).Append('\n')
            .Append("namespace ").Append(@namespace).Append(";\n")
            .Append('\n')
            .Append("internal static partial class ").Append(className).Append('\n')
            .Append("{\n")
            .Append("    public const string Json = ").Append(CSharpLiteral.Quote(CanonicalCatalogWriter.Write(document))).Append(";\n")
            .Append('\n')
            .Append("    public static global::NetPrints.Reflection.ITypeCatalog Create() =>\n")
            .Append("        global::NetPrints.Catalog.CatalogLoader.LoadJson(Json);\n")
            .Append("}\n")
            .ToString();
    }

    private static bool IsIdentifier(string name) => SyntaxFacts.IsValidIdentifier(name) && SyntaxFacts.GetKeywordKind(name) == SyntaxKind.None;
}
