using System;
using System.Text;

namespace NetPrints.Catalog;

/// <summary>
/// Emits the source that embeds a catalog in the consuming assembly (contracts/annotations.md §3): the assembly attribute
/// that discovery reads and the <c>NetPrintsCatalogs.&lt;Accessor&gt;</c> members. The JSON is a string only in the
/// attribute argument (metadata blob, UTF-8) and a <c>byte[]</c> initializer (raw data) in the accessor, never a
/// <c>const string</c>, so the user string heap limit (CS8103) is not reached. The file compiles at C# 7.3. Shared source: no file access.
/// </summary>
internal static class EmbeddedCatalogEmitter
{
    public const string AccessorClassName = "NetPrintsCatalogs";

    private const string Header = "// <auto-generated/> NetPrints.Annotations";

    private const string AttributeName = "global::NetPrints.Annotations.NetPrintsEmbeddedCatalogAttribute";

    private const string NamespacedMemberIndent = "        ";

    private const string NamespacedClassIndent = "    ";

    private const string GlobalMemberIndent = "    ";

    /// <summary>Emits the file for <paramref name="document"/>.</summary>
    /// <param name="document">The catalog.</param>
    /// <param name="rootNamespace">The namespace of the accessor class; the global namespace when null, empty or not a valid namespace.</param>
    /// <param name="accessorName">The accessor member name, a valid identifier: <c>&lt;Name&gt;</c> is the JSON text and <c>&lt;Name&gt;Utf8</c> its bytes.</param>
    /// <returns>The file text, LF line endings, ending in a newline; the same text for the same catalog.</returns>
    public static string Emit(CatalogDocument document, string? rootNamespace, string accessorName)
    {
        Guard.NotNull(document, nameof(document));
        Guard.NotNull(accessorName, nameof(accessorName));
        if (!CatalogCSharpEmitter.IsValidClassName(accessorName))
        {
            throw new ArgumentException($"'{accessorName}' is not a valid accessor name.", nameof(accessorName));
        }

        string json = CanonicalCatalogWriter.Write(document);
        bool hasNamespace = rootNamespace is { Length: > 0 } && CatalogCSharpEmitter.IsValidNamespace(rootNamespace);
        string indent = hasNamespace ? NamespacedMemberIndent : GlobalMemberIndent;
        string classIndent = hasNamespace ? NamespacedClassIndent : string.Empty;
        StringBuilder builder = new StringBuilder()
            .Append(Header).Append('\n')
            .Append("[assembly: ").Append(AttributeName).Append('(')
            .Append(CSharpLiteral.Quote(document.Id)).Append(", ")
            .Append(document.SchemaVersion.ToString(System.Globalization.CultureInfo.InvariantCulture)).Append(", ")
            .Append(CSharpLiteral.Quote(json)).Append(")]\n")
            .Append('\n');
        if (hasNamespace)
        {
            builder.Append("namespace ").Append(rootNamespace).Append('\n').Append("{\n");
        }

        builder
            .Append(classIndent).Append("internal static partial class ").Append(AccessorClassName).Append('\n')
            .Append(classIndent).Append("{\n")
            .Append(indent).Append("public static byte[] ").Append(accessorName).Append("Utf8 { get; } = ");
        CSharpLiteral.AppendUtf8Array(builder, json, indent);
        builder
            .Append(";\n")
            .Append('\n')
            .Append(indent).Append("public static string ").Append(accessorName)
            .Append(" => global::System.Text.Encoding.UTF8.GetString(").Append(accessorName).Append("Utf8);\n")
            .Append(classIndent).Append("}\n");
        if (hasNamespace)
        {
            builder.Append("}\n");
        }

        return builder.ToString();
    }

    /// <summary>Derives the default accessor name from a catalog id: each run of letters and digits capitalized and joined (<c>my-lib.core</c> is <c>MyLibCore</c>).</summary>
    /// <param name="id">The catalog id.</param>
    /// <returns>A valid identifier; <c>Catalog</c> when the id has no letter or digit, prefixed with <c>_</c> when it would start with a digit or be a keyword.</returns>
    public static string DefaultAccessorName(string id)
    {
        Guard.NotNull(id, nameof(id));
        StringBuilder builder = new();
        bool upper = true;
        foreach (char c in id)
        {
            if (!char.IsLetterOrDigit(c))
            {
                upper = true;
                continue;
            }

            builder.Append(upper ? char.ToUpperInvariant(c) : c);
            upper = false;
        }

        if (builder.Length == 0)
        {
            return "Catalog";
        }

        string name = char.IsDigit(builder[0]) ? "_" + builder : builder.ToString();
        return CatalogCSharpEmitter.IsValidClassName(name) ? name : "_" + name;
    }
}
