<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ApplicationIcon>NetPrintsLogo.ico</ApplicationIcon>
    <AssemblyName>NetPrints.Desktop</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NetPrints.Editor\NetPrints.Editor.csproj" />
  </ItemGroup>
</Project>
