<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>NetPrints.Extensibility</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <WarningsAsErrors>$(WarningsAsErrors);CA1848;CA2254</WarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NetPrints.Core\NetPrints.Core.csproj" />
    <ProjectReference Include="..\NetPrints.Reflection\NetPrints.Reflection.csproj" />
    <ProjectReference Include="..\NetPrints.Serialization\NetPrints.Serialization.csproj" />
  </ItemGroup>
</Project>
